---
services:
  apt-cacher-ng:
    image: chrisbensch/docker-aptcacherng:latest
    container_name: apt-cacher-ng
    init: true
    ports:
      - "3142:3142"
    volumes:
      - ./appdata/apt-cacher-ng/cache:/var/cache/apt-cacher-ng